@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "thangnc2",
  "password": "thangnc2",
  "email": "thang@gmail.com",
  "avatarColor": "red",
  "avatarImage": "data:image/png;base31,sflasdkfjasldkjflasdjfl",
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "thangnc2",
  "password": "thangnc2"
}

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": ""
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/<token>
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "",
  "confirmPassword": ""
}
